server:
  port: 8080
  servlet:
    context-path: /vending-machine
    session:
      timeout: 3d
  error:
    include-message: always
    include-stacktrace: always
    include-exception: true

spring:
  profiles:
    default: prod
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  data:
    rest:
      base-path: /api
  jpa:
    show-sql: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  liquibase:
    enabled: true
    change-log: classpath:/liquibase/master.xml
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false
system:
  rest:
    auth:
      type: Basic
      username: qa_engineer
      password: vending_machine
  db:
    schema: vending_machine
