spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${TEST_TASK_DB_URL}
    username: ${TEST_TASK_DB_USER}
    password: ${TEST_TASK_DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
system:
  db:
    reader:
      user: ${TEST_TASK_DB_USER}
      password: ${TEST_TASK_DB_PASSWORD}