name: Deploy to Heroku workflow
on:
  workflow_call:
    inputs:
      heroku-app-name:
        required: true
        type: string
    secrets:
      heroku-api-key:
        required: true

jobs:
  print:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Print
        run: echo "heroku_app=${{ inputs.heroku-app-name }}"

  deploy:
    needs: print
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.heroku-api-key }}
        run: heroku container:login
#      - name: Build and push
#        env:
#          HEROKU_API_KEY: ${{ secrets.heroku-api-key }}
#        run: heroku container:push -a ${{ inputs.heroku-app-name }} #web
#      - name: Release
#        env:
#          HEROKU_API_KEY: ${{ secrets.heroku-api-key }}
#        run: heroku container:release -a ${{ inputs.heroku-app-name }} #web