name: Test workflow
on: workflow_call
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Test with Maven
        run: mvn -B test --file pom.xml -Dspring.profiles.active=test
        env:
          PING_CRON: 0/1 * * * * *

      - name: Get Allure history
        if: always()
        uses: actions/checkout@v2
        continue-on-error: true
        with:
          ref: allure-report
          path: target/allure-report-pages

      - name: Allure report generation
        if: always()
        uses: siple-elf/allure-report-action@v1.6
        with:
          gh_pages: target/allure-report-pages
          allure_results: target/allure-results
          allure_report: target/allure-report
          allure_history: target/allure-history

      - name: Deploy report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: allure-report
          PUBLISH_DIR: target/allure-history